version: '3.5'
 
services:
  composer:
    build:
      context: .
    entrypoint: composer
    user: ${UID}:${GID}
    volumes:
      - .:/app

  php:
    build:
      context: .
    user: ${UID}:${GID}
    volumes:
      - .:/app

  phpstan:
    build:
      context: .
    entrypoint: phpstan
    user: ${UID}:${GID}
    volumes:
      - .:/app
