version: '3.5'
 
services:
  composer:
    build:
      context: .
    entrypoint: composer
    user: ${UID}:${GID}
    volumes:
      - .:/app

  php:
    build:
      context: .
    user: ${UID}:${GID}
    volumes:
      - .:/app

  phpstan:
    build:
      context: .
    entrypoint: phpstan analyse --level 8 src/ test/
    user: ${UID}:${GID}
    volumes:
      - .:/app

  phpunit:
    build:
      context: .
    entrypoint: ./vendor/bin/phpunit
    user: ${UID}:${GID}
    volumes:
      - .:/app
